## @section Mastodon Web Parameters
##
web:
  ## @param web.replicaCount Number of Mastodon web replicas to deploy
  ##
  replicaCount: 2


## @section Mastodon Sidekiq Parameters
##
##
sidekiq:
  ## @param sidekiq.replicaCount Number of Mastodon sidekiq replicas to deploy
  ##
  replicaCount: 2


## @section Mastodon Streaming Parameters
##
##
streaming:
  ## @param streaming.replicaCount Number of Mastodon streaming replicas to deploy
  ##
  replicaCount: 2


## @section Apache chart configuration
##
apache:
  ## @param apache.enabled Enable Apache chart
  ##
  enabled: true
