## Mastodon admin username
##
adminUser: "<YOUR_ADMIN_USER_NAME_HERE>"


## Mastodon admin password
##
adminPassword: "<YOUR_ADMIN_USER_PASSWORD_HERE>"

## Mastodon admin email
##
adminEmail: "<YOUR_ADMIN_USER_EMAIL_ADDRESS_HERE>"


## Enable the search engine (uses Elasticsearch under the hood)
##
enableSearches: true


## Enable the S3 storage engine
##
enableS3: true


## Web domain for Mastodon
## For example, visit GoDaddy and buy a valid domain to use below
##
webDomain: "<YOUR_WEB_DOMAIN_HERE>"


## Mastodon Web Parameters
##
web:
  ## Number of Mastodon web replicas to deploy
  ##
  replicaCount: 2


## Mastodon Sidekiq Parameters
##
##
sidekiq:
  ## Number of Mastodon sidekiq replicas to deploy
  ##
  replicaCount: 2


## Mastodon Streaming Parameters
##
##
streaming:
  ## Number of Mastodon streaming replicas to deploy
  ##
  replicaCount: 2


## Redis sub-chart parameters
##
redis:
  ## Deploy Redis subchart
  ##
  enabled: true


## PostgreSQL chart configuration
## ref: https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
postgresql:
  enabled: true


## MinIO chart parameters
## For full list of MinIO values configurations please refer to https://github.com/bitnami/charts/tree/main/bitnami/minio
##
minio:
  ## Enable/disable MinIO chart installation
  ## to be used as an objstore for Mastodon
  ##
  enabled: true


## Elasticsearch chart configuration
## https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/values.yaml
##
elasticsearch:
  ## Whether to deploy a elasticsearch server to use as Mastodon's search engine
  ## To use an external server set this to false and configure the `externalElasticsearch` parameters
  ##
  enabled: true


## Apache chart configuration
##
apache:
  ## Enable Apache chart
  ##
  enabled: true
  # service:
  #   annotations:
  #     service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "true"
  #     service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
  #     service.beta.kubernetes.io/do-loadbalancer-certificate-id: "<YOUR_DOCTL_COMPUTE_CERTIFICATE_ID_HERE>"
  #     service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
